services:
  app:
    build: .
    image: mcp-server
    container_name: mcp-container
    ports:
      # HOST:CONTENEDOR
      # Entras al VPS por el 8876 -> Redirige al 8765 del contenedor
      - "8876:8765"
    env_file:
      - .env
    restart: always
    volumes:
      # Mapeamos el código para cambios en caliente (opcional en prod, útil en dev)
      - ./src:/app/src
    networks:
      - shared-network

networks:
  shared-network:
    external: true