[project]
name = "mcp-server"
version = "0.1.0"
description = "Servidor MCP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai>=1.7.0",
    "fastapi>=0.124.4",
    "fastmcp>=2.12.5",
    "mysql-connector-python>=9.5.0",
    "networkx>=3.4.2",
    "openpyxl>=3.1.5",
    "python-dotenv>=1.1.1",
    "pyvis>=0.3.2",
    "uvicorn>=0.38.0",
]

[[tool.poetry.packages]]
include = "src"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
